import path from 'node:path';
import fs from 'node:fs';
import crypto from 'node:crypto';

import { sync as writeFileAtomicSync } from 'write-file-atomic';

import { getConfigValue } from './util.js';

const REGISTRATION_DIR_NAME = '_registration';
const INVITES_FILE_NAME = 'invites.json';
const INVITE_CODE_LENGTH = 8;
const INVITE_CODE_ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';

/**
 * Returns the effective registration configuration.
 * @returns {{ enabled: boolean, inviteCodes: string[], requireInvite: boolean, requireApproval: boolean, minPasswordLength: number }} Registration config
 */
export function getRegistrationConfig() {
    const codes = getConfigValue('registration.inviteCodes', []);

    return {
        enabled: getConfigValue('registration.enabled', true),
        inviteCodes: Array.isArray(codes) ? codes.filter(c => typeof c === 'string' && c) : [],
        requireInvite: getConfigValue('registration.requireInvite', false),
        requireApproval: getConfigValue('registration.requireApproval', false),
        minPasswordLength: getConfigValue('registration.minPasswordLength', 8),
    };
}

/**
 * Returns registration info for public (unauthenticated) clients.
 * @returns {{ enabled: boolean, inviteRequired: boolean, requireApproval: boolean, minPasswordLength: number }} Public registration info
 */
export function getPublicRegistrationConfig() {
    const config = getRegistrationConfig();

    return {
        enabled: config.enabled,
        inviteRequired: isInviteRequired(),
        requireApproval: config.requireApproval,
        minPasswordLength: config.minPasswordLength,
    };
}

/**
 * Returns the path to the registration storage directory.
 * @returns {string} Path to the registration directory
 */
function getRegistrationDir() {
    return path.join(globalThis.DATA_ROOT, REGISTRATION_DIR_NAME);
}

/**
 * Returns the path to the invite codes file.
 * @returns {string} Path to the invites file
 */
function getInvitesPath() {
    return path.join(getRegistrationDir(), INVITES_FILE_NAME);
}

/**
 * Reads all dynamic invite codes.
 * @returns {object[]} Invite records
 */
export function listInvites() {
    try {
        const raw = fs.readFileSync(getInvitesPath(), 'utf8');
        const invites = JSON.parse(raw);
        return Array.isArray(invites) ? invites : [];
    } catch {
        return [];
    }
}

/**
 * Persists the dynamic invite codes.
 * @param {object[]} invites Invite records
 * @returns {void}
 */
function saveInvites(invites) {
    fs.mkdirSync(getRegistrationDir(), { recursive: true });
    writeFileAtomicSync(getInvitesPath(), JSON.stringify(invites, null, 2));
}

/**
 * Generates a human-friendly invite code.
 * @returns {string} Invite code
 */
function generateInviteCode() {
    const bytes = crypto.randomBytes(INVITE_CODE_LENGTH);
    return [...bytes].map(b => INVITE_CODE_ALPHABET[b % INVITE_CODE_ALPHABET.length]).join('');
}

/**
 * Creates a new invite code.
 * @param {{ note?: string, singleUse?: boolean }} options Invite options
 * @returns {object} The created invite record
 */
export function createInvite(options = {}) {
    const invites = listInvites();
    let code = generateInviteCode();

    while (invites.some(i => i.code === code) || getRegistrationConfig().inviteCodes.includes(code)) {
        code = generateInviteCode();
    }

    const invite = {
        code,
        note: String(options.note ?? '').trim().slice(0, 200),
        singleUse: options.singleUse !== false,
        usedBy: null,
        created: Date.now(),
    };

    invites.push(invite);
    saveInvites(invites);
    return invite;
}

/**
 * Deletes a dynamic invite code.
 * @param {string} code Invite code
 * @returns {boolean} True if the code existed and was removed
 */
export function deleteInvite(code) {
    const invites = listInvites();
    const filtered = invites.filter(i => i.code !== code);

    if (filtered.length === invites.length) {
        return false;
    }

    saveInvites(filtered);
    return true;
}

/**
 * Checks whether registration requires an invite code.
 * Codes can be configured statically or generated by admins.
 * @returns {boolean} True if an invite code is required
 */
export function isInviteRequired() {
    const config = getRegistrationConfig();

    return config.requireInvite || config.inviteCodes.length > 0 || listInvites().length > 0;
}

/**
 * Validates an invite code without consuming it.
 * @param {string} code Invite code
 * @returns {boolean} True if the code is valid
 */
export function validateInvite(code) {
    if (typeof code !== 'string' || !code) {
        return false;
    }

    const config = getRegistrationConfig();

    if (config.inviteCodes.includes(code)) {
        return true;
    }

    const invite = listInvites().find(i => i.code === code);

    if (!invite) {
        return false;
    }

    return !invite.singleUse || !invite.usedBy;
}

/**
 * Consumes an invite code after a successful registration.
 * @param {string} code Invite code
 * @param {string} handle Handle of the new user
 * @returns {boolean} True if the code existed and was consumed
 */
export function consumeInvite(code, handle) {
    const invites = listInvites();
    const invite = invites.find(i => i.code === code);

    if (!invite || (invite.singleUse && invite.usedBy)) {
        return false;
    }

    if (invite.singleUse) {
        invite.usedBy = handle;
    }

    saveInvites(invites);
    return true;
}
